Configuratron:
  use_only:
    - emotion
  preload: True
  sfreq: 200
  deep1010:
    return_mask: False

#encoder_weights: Model/
#context_weights: Model/

datasets: !include configs/downstream_datasets.yml

